name: SpawnScavengerHunt
version: 1.1
main: com.cranky_dev.chatscavengerhunt.ScavengerHunt
api-version: '1.21'
commands:
  guess:
    description: Guess the hidden scavenger hunt phrase.
    usage: /guess <phrase>
  ahunt:
    description: Opens the graphical GUI control panel.
    usage: /ahunt
    permission: scavengerhunt.admin


